all:
	echo "[$(wildcard *.c)]"
	echo "[$(wildcard s?c/*.c)]"
	echo "[$(wildcard nope*.zz)]"
	echo "[$(wildcard */)]"
	echo "[$(wildcard src/)]"
	echo "[$(wildcard src/a*b*c*.c)]"
	echo "[$(wildcard Makefile/)]"
